### ISSUE TITLE
Additional formatters

### ISSUE THREAD

**Issue by zspitz** [zspitz/ExpressionTreeToString#14]
- [x] Factory methods, for C# or for VB.NET (#35)
- [x] Object notation
- [x] Built-in ToString, added in 37a4c1e
- [x] **DebugView** results <del>(pending zspitz/ExpressionTreeToString#8)</del>
- [x] Textual tree -- property path, node type, reflected type, value
- [ ] JSON
- [ ] XML, a la [Bart de Smet's `DebugView`](https://github.com/bartdesmet/ExpressionFutures/blob/master/CSharpExpressions/Docs/Debugging.MD#a-new-debugview-approach)
- [x] Dynamic LINQ (pending [this](https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/423))
